viajes: main.c crear_registro.c downloader.c crear_conexion.c  consultar_registro.c visualizar_imagen.c check.c milibreria.h
	gcc -o viajes main.c crear_registro.c downloader.c crear_conexion.c consultar_registro.c visualizar_imagen.c check.c -lcurl -I/usr/include/postgresql -lpq -std=c99 



